### ISSUE TITLE
Add HTML5

### ISSUE THREAD

**Issue by dret** [dret/webconcepts#11]
https://github.com/dret/sedola/commit/1382085f73fd79c2b0706283178cfef38fc4a561 removed an "HTML5 description" that was just a copy of html4. A proper description of HTML5 is required.

**Comment by olberger** [comment]
It is strange to see the link to HTML4 on the frontpage... whenever HTML5 seems to be the current version (unless I'm mistaken). Maybe this issue applies, then.

**Comment by dret** [comment]
On 2017-09-18 04:20, Olivier Berger wrote:
> It is strange to see the link to HTML4 on the frontpage... whenever 
> HTML5 seems to be the current version (unless I'm mistaken). Maybe this 
> issue applies, then.

thanks for the nudge. i should have done that a long time ago. it's a 
bit odd because HTML5 does not define *all* the concepts that HTML4 
defined, but of course most of them, and some more. so for now there is 
HTML4 still in there, but marked with a version, and a generic HTML 
which currently represents HTML5. and the link on the front page has 
been changed to link to that generic (the latest) version.

**Comment by dret** [comment]
closing after adding the last missing HTML5 media type: https://github.com/dret/webconcepts/commit/3c1406a1d22fecb1b5dad71d1f028654327b28a8
